spring:
  datasource:
    url: jdbc:mysql://prod-db-server:3306/university_booking_db?useSSL=true&serverTimezone=UTC
    username: springstudent
    password: ${Mahmoud@088564}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000

server:
  port: 9090

logging:
  level:
    root: WARN
    com.universityroombooking: INFO
